### ISSUE TITLE
Bug: Module does not have a module def (ɵmod property)

### ISSUE THREAD

**Issue by wvankoppen** [help-me-mom/ng-mocks#2907]
### Description of the bug

I am using ngx-translate in one of our projects. I created a wrapper around this module, which re-exports the TranslatePipe and TranslateDirective.
When I use MockBuilder to generate mocks for this module, I got the following error:

	Error: TranslateModule does not have a module def (ɵmod property)
	  ....

### A repo with an example of the bug

It can be reproduced with the following minimal test case:

```ts
import { Component, NgModule } from '@angular/core';
import { TranslateDirective, TranslateModule, TranslatePipe } from '@ngx-translate/core';

import { MockBuilder } from 'ng-mocks';

@NgModule({
  imports: [TranslateModule],
  exports: [TranslatePipe, TranslateDirective],
})
class CustomTranslateModule {}

@Component({ selector: 'mycomp', template: '' })
class MyComponent {}

@NgModule({ imports: [CustomTranslateModule], declarations: [MyComponent] })
class MyModule {}

describe('test', () => {
  beforeEach(() => MockBuilder(MyComponent, MyModule));

  it('it', () => {
    console.log('test it');
  });
});
```

### Expected vs actual behavior
Expected behavior: MockBuilder promise should resolve to the generated mocks needed for MyComponent, as declared by MyModule.
Actual behavior: The promise from MockBuilder is rejected with the error as shown above.

**Comment by satanTime** [comment]
Hi there,

Thanks for the report. I'll take a look on the weekend.

**Comment by satanTime** [comment]
Could you also provide a min repo if you have a chance?

I assume it's something related to the config of the project.

**Comment by wvankoppen** [comment]
Thanks for the quick reply. Yes, actually I created this example in the test folder in my local clone of the ngmocks repo.
I'll make sure to create a repo later today.

**Comment by satanTime** [comment]
Yep. I need a repo, a zip of a github.

es5:
```
> tests-e2e@0.0.0 test:jasmine:es5
> npm run ng test -- --ts-config ./tsconfig.es5ivy.spec.json --progress=false


> tests-e2e@0.0.0 ng
> ng

25 06 2022 10:08:47.281:INFO [karma-server]: Karma v6.4.0 server started at http://localhost:9876/
25 06 2022 10:08:47.286:INFO [launcher]: Launching browsers ChromeCi with concurrency unlimited
25 06 2022 10:08:47.293:INFO [launcher]: Starting browser ChromeHeadless
25 06 2022 10:08:53.707:INFO [Chrome Headless 104.0.5109.0 (Mac OS 10.15.7)]: Connected on socket NH3d1vk4S5O50wlQAAAB with id 70368904
LOG: 'test it'
WARN: 'Spec 'issue-2907 it' has no expectations.'
TOTAL: 1 SUCCESS
```

es2015
```
> tests-e2e@0.0.0 test:jasmine:es2015
> npm run ng test -- --ts-config ./tsconfig.es2015ivy.spec.json --progress=false


> tests-e2e@0.0.0 ng
> ng

25 06 2022 10:09:22.748:INFO [karma-server]: Karma v6.4.0 server started at http://localhost:9876/
25 06 2022 10:09:22.751:INFO [launcher]: Launching browsers ChromeCi with concurrency unlimited
25 06 2022 10:09:22.756:INFO [launcher]: Starting browser ChromeHeadless
25 06 2022 10:09:23.274:INFO [Chrome Headless 104.0.5109.0 (Mac OS 10.15.7)]: Connected on socket jPvE80kst6-kx2_XAAAB with id 9363783
LOG: 'test it'
WARN: 'Spec 'issue-2907 it' has no expectations.'
TOTAL: 1 SUCCESS
```

**Comment by wvankoppen** [comment]
I tried to create a StackBlitz to reproduce the error, but in StackBlitz it is running perfectly.
https://stackblitz.com/edit/github-rh6cyc?file=src%2Ftest.ts,src%2Ftest.spec.ts

Could you give me a pointer to which project config could be causing the problem?

**Comment by satanTime** [comment]
Could you try to run: npx ngcc? And then tests?
Maybe there is a need to compile some dependencies.

**Comment by wvankoppen** [comment]
In my mininal testcase (the code I posted above) your suggestion worked!
After running ngcc, the test ran without any error.

However, in my original monorepo the issue still exists. Any other suggestion that I can try?

**Comment by satanTime** [comment]
Hi. Please check of you have .angular directories and try to delete them before running ngcc and tests

**Comment by wvankoppen** [comment]
Thanks, I removed the .angular directory (and also the node_modules followed by an npm install), but with no luck.

Anything else that I can try?

**Comment by wvankoppen** [comment]
yes, absolutely! I just sent you an email.

**Comment by satanTime** [comment]
Hi @wvankoppen, have you been able to find a solution for your issue?

**Comment by wvankoppen** [comment]
hi @satanTime , unfortunately not, would you still like to have a look at it together?

**Comment by satanTime** [comment]
sure, starting Monday I'm available almost at any time. Please, send here a comment and we can have a call together.

**Comment by wvankoppen** [comment]
would have a gmeet at 13:00 work for you?

Meeting url: https://meet.google.com/tog-xves-uoy

**Comment by wvankoppen** [comment]
@satanTime please write me which time would work for you, thanks.

**Comment by satanTime** [comment]
In 5 mins?

**Comment by wvankoppen** [comment]
souds good! See you in 5 min in the gmeet call above :)

**Comment by satanTime** [comment]
I'm there

**Comment by wvankoppen** [comment]
@satanTime Thanks for the help this afternoon.
Small status update: I'm working on a reproducable test case of the problem in the ng-mocks repo. I haven't finished it yet, I'll send it to you later this week.

**Comment by satanTime** [comment]
Hi @wvankoppen, I hope life is good, and I wanted to check whether you had a chance to create a min repo with the issue.

**Comment by wvankoppen** [comment]
hi @satanTime! 
I kindof underestimated the effort for providing a minimal test case. 

I first tried to prune my existing repo, but it is so big that I ran into dependency problems in which the tests no longer ran at all.
So I moved back to the approach of creating a new repo and trying to introducing the same error.
Please find the attachement. I did not manage to get Jest up and running, but the errror occurs when creating a mock for a component that gets the localization service injected.

Unfortunately I could not get Jest up and running. 
Let me know whether you can reproduce the problem using this repo.

[ex.tar.gz](https://github.com/help-me-mom/ng-mocks/files/9141906/ex.tar.gz)

**Comment by satanTime** [comment]
Hi @wvankoppen, could you also share it with node_modules? Because you are using own registry, I cannot download all dependencies.

**Comment by wvankoppen** [comment]
Hi @satanTime , sorry I removed them to meet the file size constrains.
Here is a new upload: https://we.tl/t-DReRMWRWnG

**Comment by satanTime** [comment]
Hi @wvankoppen, I'm very sorry, could you re-upload it? "Transfer expired. Sorry, this transfer has expired and is not available any more".

**Comment by wvankoppen** [comment]
@satanTime yes, please see here: https://we.tl/t-Yx7Dko7vdN

**Comment by satanTime** [comment]
Thank you, I've got it!

**Comment by satanTime** [comment]
Hi @wvankoppen, could you tell me the steps, looks like it works for me:

```
npm run start

> ngx-translate-ex@0.0.0 start
> ng serve

⠙ Generating browser application bundles (phase: setup)...
- @ngx-translate/core [es2015/esm2015] (git+https://github.com/ngx-translate/core.git)
✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size
vendor.js             | vendor        |   2.37 MB |
polyfills.js          | polyfills     | 315.28 kB |
styles.css, styles.js | styles        | 207.83 kB |
runtime.js            | runtime       |   6.53 kB |
main.js               | main          |   5.69 kB |

                      | Initial Total |   2.89 MB

Build at: 2022-08-06T06:27:41.258Z - Hash: d18da66e5238fbc4 - Time: 29373ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✔ Compiled successfully.
✔ Browser application bundle generation complete.

5 unchanged chunks

Build at: 2022-08-06T06:27:42.799Z - Hash: d18da66e5238fbc4 - Time: 777ms

✔ Compiled successfully.
```

or 

```
npm run build

> ngx-translate-ex@0.0.0 build
> ng build

✔ Browser application bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.

Initial Chunk Files           | Names         |  Raw Size | Estimated Transfer Size
main.012c26427710c40f.js      | main          | 248.14 kB |                53.74 kB
polyfills.c90a33f9fab2ff8e.js | polyfills     |  33.08 kB |                10.67 kB
runtime.cd9b176e14871d3a.js   | runtime       |   1.06 kB |               605 bytes
styles.ef46db3751d8e999.css   | styles        |   0 bytes |                       -

                              | Initial Total | 282.28 kB |                65.00 kB

Build at: 2022-08-06T06:29:28.396Z - Hash: 83d5a1266bf8950c - Time: 22724ms
```

or 

```
npm run test:es5

> ngx-translate-ex@0.0.0 test:es5
> jest -w 1 --config jest.es5ivy.js

ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
 PASS  src/app/app.component.spec.ts (5.056 s)
  AppComponent
    ✓ should create the app (87 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        6.381 s
Ran all test suites.
```

I do still believe this is a misconfiguration of your project. Let's have a call next week and check how the jest is configured.
Because in the repo you provided I needed:
- install `jest@28`
- install `jest-preset-angular@^12`
- configure them together

**Comment by satanTime** [comment]
Th-Mo I'm out in Berlin. Would it work Tu/We this week? or we can try to catch up next week at an evening.

**Comment by wvankoppen** [comment]
Today and Wednesday I'm already fully scheduled, lets catch up next week then? What about Monday at 20:00?

**Comment by satanTime** [comment]
Sounds good, let's have a call by then.

**Comment by satanTime** [comment]
Hi there, I just found out that I'm still going to be at airport by that time. Let's move it to Tuesday at the same time, if you don't mind.

**Comment by wvankoppen** [comment]
yes, perfect :)

**Comment by wvankoppen** [comment]
hi @satanTime , hereby the meeting: https://meet.google.com/kdc-jyas-qkc
See you there.

**Comment by satanTime** [comment]
For history:

we had a call and were able to isolate the failure, now I'm waiting for a min repo without project's components to investigate and fix the issue.

**Comment by wvankoppen** [comment]
hi @satanTime!

Sorry for the delay. I had to redo the minification a few times over and over, as the first attempts ended up too minimal to reproduce.
See the tar file: https://we.tl/t-TirIPqo3dO, let me know how it went.
Could you remove any leftovers after the problem is pinpointed?

Thanks a lot!

**Comment by wvankoppen** [comment]
@satanTime I hope your'e doing fine?
Just want to let you know I'm on holiday for the next 2 weeks, and thus not being able to reply.

**Comment by satanTime** [comment]
Hi @wvankoppen,

I hope your vacation was good.

Finally, I got time to check the issue, but the same story - `npm install` returns `ERR code 401` and cannot install all packages.
Could you provide me a copy of `node_modules` directory of the min project?

**Comment by satanTime** [comment]
When I've removed the private package, I get the next error:

```
    NullInjectorError: R3InjectorError(DynamicTestModule)[PrivaLocalizationService -> PrivaLocalizationService]:
      NullInjectorError: No provider for PrivaLocalizationService!
```

and when I added it to `MockBuilder` as

```ts
    beforeEach(() => {
        console.log(123);
        // TODO: WvK: Provide a mock of the PrivaQueryableDataSource as input to the component
        return MockBuilder(PrivaFilterDateComponent, [PrivaFilterDateModule, PrivaLocalizationService]);
    });
```

I'm getting

```
npm run test:jest:debug --project components

> @priva/monorepo-workspace@7.0.0 test:jest:debug
> npm run test:jest -- --detectOpenHandles


> @priva/monorepo-workspace@7.0.0 test:jest
> jest --coverage --maxWorkers=4 --passWithNoTests

Determining test suites to run...
ngcc-jest-processor: running ngcc
Warning: Entry point 'ng2-date-picker' contains deep imports into '/Users/michael/Downloads/temp/priva.packages.monorepo-2/node_modules/moment/moment'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
  console.log
    123

      at projects/components/filter/src/lib/components/filters/date/filter-date.component.spec.ts:206:17

 PASS   priva.packages  projects/components/filter/src/lib/components/filters/date/filter-date.component.spec.ts
  FilterDateComponent
    ✓ should create (79 ms)

-----------------------------------------|---------|----------|---------|---------|-------------------
File                                     | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-----------------------------------------|---------|----------|---------|---------|-------------------
All files                                |   92.59 |    57.14 |   33.33 |   95.23 |
 localization                            |     100 |      100 |     100 |     100 |
  index.ts                               |     100 |      100 |     100 |     100 |
 localization/src                        |     100 |      100 |       0 |     100 |
  public-api.ts                          |     100 |      100 |       0 |     100 |
 localization/src/lib/priva-translation  |   77.77 |        0 |       0 |   83.33 |
  priva-translation.module.ts            |   77.77 |        0 |       0 |   83.33 | 24
 localization/src/lib/shared/preferences |     100 |      100 |     100 |     100 |
  meridiem.enum.ts                       |     100 |      100 |     100 |     100 |
  weekstart.enum.ts                      |     100 |      100 |     100 |     100 |
-----------------------------------------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.848 s, estimated 5 s
Ran all test suites matching /components/i.
```

**Comment by wvankoppen** [comment]
Hi @satanTime!

Thanks for your reply, I retried it as well.. and I got the sime output as you do.
I think we should close the issue for now, as the issue no longer seem to be reproducible.
But thanks for analyzing!

**Comment by satanTime** [comment]
Hi @wvankoppen, oki. Feel free to reopen it if you are facing the issue again.

**Comment by wvankoppen** [comment]
@satanTime thanks a lot!
Btw, your last posts contain the company name "Priva" and disclose some details of the sources that I sent you. 
Could you please truncate or delete this from those 2 posts such that they don't disclose any details regarding the sources that I provided?

(Otherwise I might get troubles about this as it is publicly on the internet)

**Comment by satanTime** [comment]
Hi @wvankoppen, sorry about that. I've deleted the comments.

**Comment by wvankoppen** [comment]
@satanTime thanks!
