### ISSUE TITLE
Bug: MockBuilder a standalone component that imports a standalone directive, it fails

### ISSUE THREAD

**Issue by trystan2k** [help-me-mom/ng-mocks#3100]
### Description of the bug

When mocking a standalone directive imported by a standalone component, an error is throw saying that MockOfDirective is not standalone

`Error: The "MockOfTestDirective" directive, imported from "TargetComponent", is not standalone. Did you forget to add the standalone: true flag?`

### An example of the bug

https://stackblitz.com/edit/github-7zh6cj?file=src%2Ftest.spec.ts

Link:

### Expected vs actual behavior

Since the original imported directive (TestDirective) is a standalone: true directive, the mocked version (MockOfTestDirective) should also be a standalone and the MockBuilder should be able to mock it as expected.

Not sure if I am missing anything or doing something wrong, but I did the same test with a standalone Pipe and it worked ok. 
Is this scenario already supported ? 
What I could be doing wrong here ?

Thanks !

**Comment by satanTime** [comment]
Hi @trystan2k,

thanks for reporting the issue. The fix will be released within next hours.

**Comment by satanTime** [comment]
[v14.1.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.1.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by trystan2k** [comment]
Hi @satanTime,

I just tested it and it worked perfectly !

Thanks you very much !!!
