### ISSUE TITLE
mockRender() call resulting in error

### ISSUE THREAD

**Issue by mdv27** [help-me-mom/ng-mocks#3131]
### Discussed in https://github.com/help-me-mom/ng-mocks/discussions/3130

<div type='discussions-op-text'>

<sup>Originally posted by **mdv27** July 19, 2022</sup>
I am using ng-mocks functions to write unit test for angular component. It was working before angular version update from 11 to 12.
Test failing with below error stack:

![image](https://user-images.githubusercontent.com/12114755/179738146-bd515e45-ce15-4be4-a4ff-da74246cf711.png)

versions before and after:
|Dependency|Before|After|
| ------------- |:-------------:| -------------:| 
|typescript | 4.0.8| 4.3.5|
|@angular-devkit/build-angular |0.1100.5 | 12.2.17|
|@angular/cli|11.0.5|12.02.17|
|@angular/compiler-cli|11.0.5|12.2.16|
|@angular/common|11.x.x|12.x.x|
|@angular/core|11.x.x|12.x.x|
|@angular/compiler|11.x.x|12.x.x|
|@angular/forms|11.x.x|12.x.x|
|@angular/localize|11.x.x|12.x.x|
|@angular/platform-browser|11.x.x|12.x.x|
|@angular/platform-browser-dynamic|11.x.x|12.x.x|
|@angular/router|11.x.x|12.x.x|

Test example:

```js
 it('should create component', () => {
    const fixture = MockRender(myComponent, {});
    const component = fixture.point.componentInstance;
    expect(component).toBeDefined();  
  });
```
Please help. </div>

**Comment by satanTime** [comment]
Hi @mdv27,

thanks for moving it to be an issue. Could you add a min repo how to reproduce it?

**Comment by mdv27** [comment]
I found the issue, @angular-builders/jest dependency was 14.x.x, switched to 12.x.x. Surprisingly it worked fine with Angular 11.x.x
Closing this as its fixed now.
