### ISSUE TITLE
ngMocks.globalReplace doesn't seem to replace in standalone component

### ISSUE THREAD

**Issue by DW8Reaper** [help-me-mom/ng-mocks#3161]
### Description

I apologize that I don't have an easy reproduction added here but the basic issue is the following, when using standalone components (testing with NgMocks v14.1.0) any ngMocks.globalReplace calls don't seem to apply to those components.

So in our codebase we do a global setup that calls something like this:
```javascript
ngMocks.globalReplace(TranslateModule, MockTranslateModule);
```

Then in our code we have a standalone component:
```javascript
@Component({
  select: 'a-component',
  template: '',
  standalong: true,
  imports: [TranslateModule]
})
```

and the test setup for the standalone component
```javascript
  beforeEach(() => {
    return MockBuilder(TheStandaloneComponent);
  });
```

However the test don't work because when the tests run it uses vanilla/automatic module mocks for the TranslateModule instead of using my global replacement.

### Workaround
I can work around it by adding a replace directly in the test like this then it works again:
```javascript
  beforeEach(() => {
    return MockBuilder(TheStandaloneComponent).replace(TranslateModule, MockTranslateModule);
  });
```

**Comment by DW8Reaper** [comment]
Thanks @satanTime I don't know if this helps or further confuses the issue but I have found anther funky thing might be related/causing this. If we have code like this:
```javascript
mockBuilder(SomeComponent, SomeModule)
      .mock(SomeService, aCustomMockObjectWeMake)
```
but the module SomeModule does not define or export SomeService (in fact no module in the test exports it). Previously it seems when we call .mock(SomeService, aCustomMockObjectWeMake) it would also automatically define a provider for that service if it didn't exist. 

I can fix it by doing this which I didn't need in ngMocks v13.0.3
```javascript
mockBuilder(SomeComponent, SomeModule)
      .mock(SomeService, aCustomMockObjectWeMake, {export: true})
```

So possibly there is a change to how that mock method works with services that aren't directly imported in any module in the test. I don't know if this is possibly related or causing the standalone component issue as well.

I realize that maybe we should not be using ngMocks.mock with a service that isn't registered in any modules

**Comment by satanTime** [comment]
Hi @DW8Reaper, I hope this finds you well.

the fix is here.

Regarding `MockBuilder(SomeComponent, SomeModule).mock(SomeService, aCustomMockObjectWeMake)`, this is a breaking change in `ng-mocks@14.x`. if you specify 2 parameters in `MockBuilder`, then chain calls expect all declarations to be a part of those 2 parameters: https://ng-mocks.sudo.eu/migrations#from-13-to-14

Basically, you need to add `SomeService` to the 2nd parameter for mocks:

```ts
MockBuilder(SomeComponent, [SomeModule, SomeService]).mock(SomeService, aCustomMockObjectWeMake);
```

Then, it's clear that it's an external dependency and neither `SomeComponent` nor `SomeModule` provides it.

**Comment by satanTime** [comment]
[v14.1.1](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.1.1) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by DW8Reaper** [comment]
Thanks @satanTime I missed that breaking change from 13 to 14 so that's my bad on that one, thanks for fixing the global mocks that looks like the change you made in v14.1.1. I'll give it a shot and update our mocks based on the required migrations and see how it works

**Comment by satanTime** [comment]
Sounds good! Thanks in advance!
