### ISSUE TITLE
Documentation: document that MockInstance works with "classic tools"

### ISSUE THREAD

**Issue by undsoft** [help-me-mom/ng-mocks#3391]
Currently `MockInstance` is in the separate section from classic tools and has no usage examples with `MockComponent`. This leads user to think that that they don't work together, when they do.

Even if you try to test yourself if they can work together, all examples usually have `MockInstance` being run in `beforeEach`, which won't work if you run `TestBed.configureTestingModule` outside of `beforeEach`.

Suggestion: add an example where `MockInstance` is used together with `MockComponent` and `TestBed.configureTestingModule`.

**Comment by satanTime** [comment]
[v14.2.3](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.2.3) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
