### ISSUE TITLE
Bug: ng test fails to run because of ng-mocks error after upgrading to typescript 4.8.2

### ISSUE THREAD

**Issue by fagia** [help-me-mom/ng-mocks#3514]
### Description of the bug

With devDependency on ng-mocks 14.2.0, after upgrading to typescript 4.8.2, `ng test` fails to run with the following error:

```
Error: node_modules/ng-mocks/index.d.ts:1447:112 - error TS2344: Type 'C' does not satisfy the constraint 'Record<string | number | symbol, any>'.

1447 export interface MockedComponentFixture<C = Record<string | number | symbol, any >, F = DefaultRenderComponent<C>> extends ComponentFixture<F> {
                                                                                                                    ~

  node_modules/ng-mocks/index.d.ts:1447:41
    1447 export interface MockedComponentFixture<C = Record<string | number | symbol, any >, F = DefaultRenderComponent<C>> extends ComponentFixture<F> {
                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    This type parameter might need an `extends Record<string | number | symbol, any>` constraint.
```

Everything works fine just downgrading typescript version to 4.7.4

**Comment by satanTime** [comment]
Hi @fagia,

Thanks for the report.
Please, provide a min repo with the issue.

**Comment by fagia** [comment]
Hi @satanTime 
thanks for your answer, I've been able to reproduce the same issue with ng-mocks repo itself:
- check-out master
- in package.json update the typescript dependency to 4.8.2
- npm run build -- --prod
- same error will happen

I've also tried to make few changes to ng-mocks sources to make typescript 4.8.2 happy...they seem to work but, since I'm not having full context, I'm not sure that they would not breaking anything else... in case, these are the changes I've tried are attached here:
[ng-mocks_issue_3514.patch.zip](https://github.com/help-me-mom/ng-mocks/files/9525447/ng-mocks_issue_3514.patch.zip)

**Comment by satanTime** [comment]
https://app.circleci.com/pipelines/github/help-me-mom/ng-mocks-sandbox/1604/workflows/04111b3d-a324-4b5b-b9bd-1f8e4faa719a/jobs/2473

**Comment by satanTime** [comment]
[v14.2.1](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.2.1) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by fagia** [comment]
Cool I can confirm that it's now working fine!
Thanks @satanTime for the quick and effective fix
