### ISSUE TITLE
Bug: Required and renamed component input causes tests to fail after Anguar update

### ISSUE THREAD

**Issue by Tukkan** [help-me-mom/ng-mocks#3515]
### Description of the bug

When moved from 14 to 14.1/14.2 I can see strange behaviour when executing tests with components.
When having component with required, renamed input one of the tests always fails.

```
@Component({
  selector: 'app-target[templateName]', // set as required
  template: ``,
})
class TargetComponent {
  @Input('templateName') public internalName: string; // renamed input
}
```

Seems like MockRender does not work correctly with required and renamed inputs as it makes them undefined.
```
ERROR: 'NG0304: 'ng-mocks-TargetComponent ' is not a known element (used in the 'n' component template):
1. If 'ng-mocks-TargetComponent ' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
2. If 'ng-mocks-TargetComponent ' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'
```

Please check the stackblitz example to exactly see what I mean.

### An example of the bug

Working example: https://stackblitz.com/edit/github-w2g2h7?file=src/test.spec.ts

**Comment by satanTime** [comment]
Hi @Tukkan,

thanks for the report. The issue has been fixed already. Please wait for the next release.

**Comment by satanTime** [comment]
[v14.2.1](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.2.1) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by Tukkan** [comment]
Thank you for quick reaction. Cheers.
