### ISSUE TITLE
Bug: Cannot find TargetService via ngMocks.get

### ISSUE THREAD

**Issue by endarice** [help-me-mom/ng-mocks#3628]
### MockBuilder is unable to find services provided through a parent component

When using the `mock()` method on `MockBuilder` to mock a service provided in a parent component MockBuilder is unable to find it.
![image](https://user-images.githubusercontent.com/11618868/190709705-09742585-ad4c-4b61-9cf4-2c65c95ec27a.png)
When using the `provide()` method on `MockBuilder` it is able to provide the service but when using with `useValue:` and `MockedInstance` as described [here](https://github.com/help-me-mom/ng-mocks/issues/198) it doesn't use the mocked service correctly.

### Example

```
import { Component, Injectable } from '@angular/core';

import { MockBuilder, MockRender, ngMocks } from 'ng-mocks';

// A simple service, might have contained more logic,
// but it is redundant for the test demonstration.
@Injectable()
class TargetService {
  public value = 'target';
}
@Component({
  providers: [TargetService],
  selector: 'parent',
  template: '<target></target>',
})
class ParentComponent {
}

@Component({
  selector: 'target',
  template: '{{ service.value }}',
})
class TargetComponent {
  public constructor(public readonly service: TargetService) {}
}

describe('TestProviderInComponent', () => {

  beforeEach(() => MockBuilder(TargetComponent).mock(TargetService, {value: 'a'}));

  it('has access to the service via a component', () => {
    // Let's render the mock component. It provides a point
    // to access the service.
    const fixture = MockRender(TargetComponent);

    // The component's element is fixture.point.
    // Now we can use ngMocks.get to extract internal services.
    const service = ngMocks.get(fixture.point, TargetService);

    // Here we go, now we can assert everything about the service.
    expect(service.value).toEqual('a');
  });
});
```

**Comment by satanTime** [comment]
Hi, thanks for the report.

However, this is not a bug, in your code, `ngMocks.get(fixture.point, TargetService);` expects that `TargetService` is provided on the level of `TargetComponent`, but it's not true, because `TargetService` is provided globally on `fixture`.

To get its instance you need to use:

```ts
const service = ngMocks.get(TargetService);
```
or
```ts
const service = ngMocks.get(fixture, TargetService);
```
