### ISSUE TITLE
Consider making Type<T> public again

### ISSUE THREAD

**Issue by marklbarlow** [help-me-mom/ng-mocks#3709]
We use ng-mocks to create re-usable mock modules so we don't need to repeat our mocking set-up across apps.  This is done using standard Angular CLI library projects and `ng-packagr`.

Since v14, the following interface is no long public:

```typescript
export interface Type<T> extends Function {
  new (...args: any[]): T;
}
```

This means that usage such as the below is no longer possible:

```typescript
export const FooTestingModule = MockModule(FooComponentsModule);
```

Compilation now results in the following error:

`Exported variable 'FooTestingModule ' has or is using name 'Type' from external module "E:/code/Foo/node_modules/ng-mocks/index" but cannot be named.`

Could this interface be made public again or a different approach suggested to satisfy the above requirement?

**Comment by marklbarlow** [comment]
Hi @satanTime,

I've created an example at https://github.com/marklbarlow/ng-mocks-example

You just need to:
`npm install`
`ng build example`

**Comment by satanTime** [comment]
Hi @marklbarlow, thank you for the repo.

now I see the problem. Is there a reason why you put mocks in the production build?

Usually, I would expect `ng-mocks` in tests only.

**Comment by marklbarlow** [comment]
Hi @satanTime , we put mocks in a production build as we're creating a set of re-usable mocks that can be used across all our apps.  Without this we need to repeat our mocking set up / definitions a dozen times across our various repos...

**Comment by satanTime** [comment]
oki-doki. I'll implement a test and return back the exports of required types.

`Type<T>` was hidden to avoid imports from `ng-mocks`, because it exists in `@angular/core` and basically should be imported from there.

I'll try to add jsdoc to let users know about the right import, if it's possible.

**Comment by satanTime** [comment]
[v14.2.4](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.2.4) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
