### ISSUE TITLE
Bug: Standalone CVA component

### ISSUE THREAD

**Issue by kekel87** [help-me-mom/ng-mocks#3778]
### Description of the bug

Hi 🙃, I was migrating most of my dumb components to Standalone.

But the tests of the ones implementing `ControlValueAccessor` won't start.

I've got this error:
```
TypeError: Cannot read properties of undefined (reading 'constructor')
```
I also tried with NgModel without success (see in example).

Thanks !

### An example of the bug

Link: https://stackblitz.com/edit/github-gdvfn5?file=src%2Ftest.spec.ts

### Expected vs actual behavior

That the CVA standelone component can be tested with ng-mocks.

**Comment by satanTime** [comment]
Hi @kekel87,

thanks for the report. You need to keep `NG_VALUE_ACCESSOR` too for now.
I'll be working on a fix to automatically mark `NG_VALUE_ACCESSOR` as kept if it's possible.

The thing is that `providers` of `StandaloneCVAComponent` are replaced with mocks, but I think if the providers point to the same class, then it can stay as it is.

**Comment by satanTime** [comment]
[v14.2.4](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.2.4) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by kekel87** [comment]
Thank you very much for your reactivity. Have a good week.

**Comment by satanTime** [comment]
You too! Stay in touch!

**Comment by LukasMachetanz** [comment]
We are using version `^14.6.0` of ng-mocks and experience the same problem. Can you certainly confirm that this issue is resolved?

**Comment by satanTime** [comment]
Hi @LukasMachetanz, could create a min example of the issue? Feel free to submit a new bug.
