### ISSUE TITLE
Bug: Test fails if executed independently '__ngContext__={[Function Number]}' vs '__ngContext__="0"'

### ISSUE THREAD

**Issue by jones1008** [help-me-mom/ng-mocks#3811]
### Description of the bug

from https://stackoverflow.com/q/73307975/7987318:
>I'm currently facing a strange behavior on my Angular (14) shallow rendering snapshots in unit tests (Jest 28).

>Sometimes my snapshot tests are failing, depending if I run them individually or as bundle. The reason of failure is the difference between __ngContext__={[Function Number]} and __ngContext__="0".

```typescript
// hello.component.ts
import {Component, Input} from '@angular/core';

@Component({
  selector: 'hello',
  template: `<h1>Hello {{name}}!</h1>`
})
export class HelloComponent  {
  @Input()
  name: string;
}

```
```typescript
// hello.component.spec.ts
describe('HelloComponent', () => {
  beforeEach(() => {
    return MockBuilder(HelloComponent, AppModule);
  });

  it('should render component correctly with Joe', () => {
    const fixture = MockRender(HelloComponent, {name: 'Joe'});
    expect(fixture).toMatchSnapshot()
  });

  it('should render component correctly with other name', () => {
    const fixture = MockRender(HelloComponent, {name: 'Jane'});
    expect(fixture).toMatchSnapshot()
  });
});
```

#### reproduction steps
First clone my reproduction repo: https://github.com/jones1008/ng-mocks-snapshot-test-bug

To reproduce the bug follow these steps:
```
npm install
npm run test
npm run single-test-fail
```

See that when running `npm run test` the tests pass, and when running `npm run single-test-fail` the test fails with the following error:
```
 FAIL  src/app/components/hello.component.spec.ts
  HelloComponent
    ✕ should render component correctly with other name (66 ms)
    ○ skipped should render component correctly with Joe

  ● HelloComponent › should render component correctly with other name

    expect(received).toMatchSnapshot()

    Snapshot name: `HelloComponent should render component correctly with other name 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -1,7 +1,7 @@
      <mock-render
    -   __ngContext__={[Function Number]}
    +   __ngContext__="0"
      >
        <hello>
          <h1>
            Hello Jane!
          </h1>

      15 |   it('should render component correctly with other name', () => {
      16 |     const fixture = MockRender(HelloComponent, {name: 'Jane'});
    > 17 |     expect(fixture).toMatchSnapshot()
         |                     ^
      18 |   });
      19 | });
      20 |

      at src/app/components/hello.component.spec.ts:17:21
```

### Notes:

- `npm run single-test-fail` executes `jest -t 'HelloComponent should render component correctly with other name'` and therefore the second test in the `hello-component.spec.ts` file
- `npm run single-test-fail` executes `jest -t 'HelloComponent should render component correctly with Joe'` and therefore the first test in the `hello-component.spec.ts` file. Strangely this test passes!
- I couldn't make a StackBlitz because I was getting some StackBlitz-related error when executing `npm run test`

**Comment by satanTime** [comment]
Hi @jones1008,

thank you for the report.

However, it looks like an issue in Angular or jest, but not in `ng-mocks`.
The next test without `ng-mocks` fails in the same way:

```ts
import {HelloComponent} from "./hello.component";
import {TestBed} from "@angular/core/testing";

describe('HelloComponent', () => {
  beforeEach(() => TestBed.configureTestingModule({
    declarations: [HelloComponent],
  }).compileComponents());

  it('should render component correctly with Joe', () => {
    const fixture = TestBed.createComponent(HelloComponent);
    fixture.componentInstance.name = 'Joe';
    fixture.detectChanges();
    expect(fixture).toMatchSnapshot()
  });

  it('should render component correctly with other name', () => {
    const fixture = TestBed.createComponent(HelloComponent);
    fixture.componentInstance.name = 'Jane';
    fixture.detectChanges();
    expect(fixture).toMatchSnapshot()
  });
});
```

It looks like, the very first call of `TestBed.createComponent` uses a pure number, whereas the second and following use it as a Number object.

I would suggest to report the issue to Angular / jest, not sure which of them convert the number to an object.

**Comment by satanTime** [comment]
It looks like, I found a way to remove `__ngContext__` from the final snapshot.

Could you check if it works well in your project?
The build: [ng-mocks.zip](https://github.com/help-me-mom/ng-mocks/files/9774757/ng-mocks.zip)

**Comment by jones1008** [comment]
@satanTime Yes this works!

Does it make sense to ship this fix? Do we need `__ngContext__` in our snapshot files? Is it maybe even good if we remove it?

Also when you ship this, all the snapshot tests that were setup with ng-mocks will fail. So is this a breaking change?

**Comment by satanTime** [comment]
Nice! I'm glad to hear that.

I wouldn't expect a need of `__ngContext__`, it's an internal attribute for angular core and its value shouldn't influence on your tests.

I'll ship it as it is with a note that `__ngContext__` will be removed from snapshots and it might require to update them.

**Comment by jones1008** [comment]
Great! Thanks for the quick answers and fix!

**Comment by satanTime** [comment]
[v14.3.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.3.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
