### ISSUE TITLE
Feature Request: improving description and examples for ngMocks.get

### ISSUE THREAD

**Issue by Dji75** [help-me-mom/ng-mocks#3882]
### ngMocks.get description too vague

Currently `ngMocks.get` description could be understood to only concerns structural directives or services but it can also be used for components or common directives
`declarations` word is not enough precise.

Consequently we may be tempted to use `ngMocks.findInstance` which mention components, directives and so on but in some cases we could have false positive (because debugElement or css selector is missing or present in childs), and `ngMocks.get` is more accurate (we don't want to go through childs).

### Proposed solution

I would urpose the following patch which add all of those precisions

### Additional context

[docs(get)__update_description_and_add_examples_to_get_component,_directive_or_service.patch.txt](https://github.com/help-me-mom/ng-mocks/files/9831883/docs.get.__update_description_and_add_examples_to_get_component._directive_or_service.patch.txt)

**Comment by satanTime** [comment]
Hi @Dji75,

for windows you need `gitbash`. I'll update docs about that.

Regarding you change - could you do it right on github? on the related docs page you can click "Edit this page" at the bottom of the page: https://ng-mocks.sudo.eu/api/ngMocks/get.

**Comment by satanTime** [comment]
Hi @Dji75, this issue I'm going to close with the updated `CONTRIBUTING.md`, please open a PR with the updated documentation via `Edit this page`, or ping me here if you want to discuss whatever first.

**Comment by satanTime** [comment]
[v14.3.1](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.3.1) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by Dji75** [comment]
You're right git bash works better than cmder for unix-like scripts ;)

Thanks for your feedbacks @satanTime.

Here is the corresponding PR: https://github.com/help-me-mom/ng-mocks/pull/3899
