### ISSUE TITLE
Problem with CDK since v14

### ISSUE THREAD

**Issue by BantramFidian** [help-me-mom/ng-mocks#4249]
After struggeling with
```
TypeError: Cannot read properties of undefined (reading 'subscribe')
            at new HighContrastModeDetector (node_modules/@angular/cdk/fesm2020/a11y.mjs:2356:40)
            at Object.factory (node_modules/@angular/cdk/fesm2020/a11y.mjs:2421:1)
            at R3Injector.hydrate (node_modules/@angular/core/fesm2020/core.mjs:6887:35)
            at R3Injector.get (node_modules/@angular/core/fesm2020/core.mjs:6775:33)
            at injectInjectorOnly (node_modules/@angular/core/fesm2020/core.mjs:4782:33)
            at Module.ɵɵinject (node_modules/@angular/core/fesm2020/core.mjs:4786:12)
            at Object.useFactory (node_modules/@angular/material/fesm2020/core.mjs:105:1)
            at Object.factory (node_modules/@angular/core/fesm2020/core.mjs:6974:38)
            at R3Injector.hydrate (node_modules/@angular/core/fesm2020/core.mjs:6887:35)
            at R3Injector.get (node_modules/@angular/core/fesm2020/core.mjs:6775:33)
```

For quite some time and stumbling over [this post](https://github.com/angular/components/issues/25563) over at the angular repository.
I feel like this problem should propably be approached on this side.

It seems to me that all tests remotely connected to Angular Material Components keep failing with the exact same error, caused by [this line](https://github.com/angular/components/blob/main/src/cdk/a11y/high-contrast-mode/high-contrast-mode-detector.ts#L57).

The change that caused the problem seems to be introduced by [#25088](https://github.com/angular/components/pull/25088/files) back at angular, but on their side they see the problem over here.

Hope we can at least find a workaround for the time being.

**Comment by satanTime** [comment]
Hi @BantramFidian,

I think this is related to https://github.com/help-me-mom/ng-mocks/issues/4168.

Could you provide a min repo with the issue?
Otherwise, the possible solutions are described in the issue above.

**Comment by satanTime** [comment]
Hi @BantramFidian,

I was able to reproduce the issue.

The problem here is that `BreakpointObserver` is a root service, and `ng-mocks` mocks root services by default.
It means, if you keep a mat module which imports `A11yModule`, for example `MatBadgeModule` etc, this will cause the issue.

Because the kept module will inherently keep `HighContrastModeDetector` service too.
And because `BreakpointObserver` is a mock, its `observe` method doesn't return an observable, and, therefore, it throws `Cannot read properties of undefined (reading 'subscribe')`.

Currently, you can fix it by adding `.keep(NG_MOCKS_ROOT_PROVIDERS)` to the failing tests.

And, I'll think a bit about how it's possible to make it work.

a failing test example:

```ts
import {Component, NgModule} from "@angular/core";
import {MatBadgeModule} from "@angular/material/badge";
import {MockBuilder, MockRender, NG_MOCKS_ROOT_PROVIDERS} from "ng-mocks";
import {BreakpointObserver} from "@angular/cdk/layout";

@Component({
  selector: 'target',
  template: '<label [matBadge]="777">My Label</label>'
})
class TargetComponent {
  constructor(public readonly service: BreakpointObserver) {}
}

@NgModule({
  imports: [MatBadgeModule],
  declarations: [TargetComponent],
  exports: [TargetComponent],
})
class TargetModule {}

// @see https://github.com/help-me-mom/ng-mocks/issues/4249
describe('issue-4249', () => {
  beforeEach(() => MockBuilder(TargetComponent, TargetModule).keep(MatBadgeModule)/*.keep(NG_MOCKS_ROOT_PROVIDERS)*/);

  it('creates TargetComponent', () => {
    expect(() => MockRender(TargetComponent)).not.toThrow();
  });
});
```

**Comment by satanTime** [comment]
[v14.4.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.4.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
