### ISSUE TITLE
Feature Request: Angular v14 "inject" support

### ISSUE THREAD

**Issue by ssergdev** [help-me-mom/ng-mocks#4282]
### Describe the feature or problem you'd like to solve
MockBuilder is mocking the providers defined in the component constructor but **ignoring** the providers defined with "inject" method:
```
@Injectable({providedIn: 'root'})
export class MyService{ ... }

@Component(...)
export class MyComponent{
  myService = inject(MyService)
}

describe('MyComponent', () => {
  beforeEach(() => MockBuilder(MyComponent, MyModule))

  it('should create', () => {
    const fixture = MockRender(MyComponent);
    const component = fixture.point.componentInstance;
    expect(component).toBeDefined();
  });
})
```
The way how I can mock MyService here is to define it as a context:
```
  beforeEach(() => MockBuilder(MyComponent, [MyModule, MyService])
```
### Background
```
    "ng-mocks": "14.3.3",
    "@angular/core": "14.0.4"
```

**Comment by satanTime** [comment]
Hi @ssergdev,

thanks for reporting the issue.

Could you check that this build works are you expect? [ng-mocks.zip](https://github.com/help-me-mom/ng-mocks/files/10050245/ng-mocks.zip)

**Comment by ssergdev** [comment]
Hello and thank for reply so fast! Quick test fails, tomorrow will reproduce in a separate repo.

**Comment by satanTime** [comment]
Hi, thanks for checking.

I added some improvements: [ng-mocks.zip](https://github.com/help-me-mom/ng-mocks/files/10050843/ng-mocks.zip)

**Comment by satanTime** [comment]
[v14.4.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.4.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by Francesco-Borzi** [comment]
@satanTime This bug seems to happen again on ng-mocks 14.13.0
