### ISSUE TITLE
Feature Request: allow to mock only specific methods

### ISSUE THREAD

**Issue by serhiistotskyi** [help-me-mom/ng-mocks#4367]
### Describe the feature or problem you'd like to solve

Sometimes I want to mock just one method and leave the rest of the service as is. So, it can run some domain specific logic (or side-effects)

### Proposed solution

Provide a function that has the same declaration as `MockProvider` but modifies service instead of creating a full mock:

```ts
class MyService {
  someMethod() {
       console.log('implementation')
       return of(undefined);
  }

  anotherMethod() {
        return this.someMethod().pipe(
          tap(() => {
              // side effects, changes to service properties or changes in dependencies
          })
        )
  }
}

PatchProvider(MyService, {
  someMethod: jest.fn(() => of(...))
});

// later in tests
const service = TestBed.inject(MyService);

console.log(service.someMethod) // jest.fn()
console.log(service.anotherMethod) // original method
```

Additionally would be nice to ignore `undefined` values in object, i.e., if property is `undefined` just ignore it and do not override service method/property:

```ts
PatchProvider(MyService, {
  someMethod: jest.fn(() => of(...)),
  anotherMethod: undefined // ignored, as if there is no this property at all
});
```

this allows to simplify pattern of using `setup` function and passing props inside:

```ts
function setup(props?: Props) {
   TestBed.configureTestingModule({
       providers: [
           PatchProvider(MyService, {
              someMethod: props?.someMethod
           })
       ]
    });
}

interface Props {
  someMethod?: MyService["someMethod"]
}
```

We use this pattern a lot in our codebase, together with `MockProvider`, so would be nice to have this built-in.

### Additional context

We have implemented this custom function using `APP_INITIALIZER` token:

```ts
function PatchProvider<T extends {}>(
    token: ProviderToken<T>,
    modifications: Partial<T>
): FactoryProvider {
  return {
        provide: APP_INITIALIZER,
        multi: true,
        deps: [token],
        useFactory(service: T) {
            return () =>
                Object.keys(modifications).forEach((key) => {
                    const value = (modifications as Record<string, unknown>)[key];
                    if (value === undefined) return;

                    (service as Record<string, unknown>)[key] = value;
                });
        },
    };
}
```

**Comment by satanTime** [comment]
Hi @serhiistotskyi,

thank you for the request.

I've fixed the part with `undefined`. it will be merged soon.

Regarding partial mocks, it's bad practice and isn't supported by `ng-mocks`.

**Comment by satanTime** [comment]
[v14.5.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.5.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by stalniy** [comment]
Why is it a bad practice? I’ll look into our use cases and will let you know. But I had issues with Router and routerLink when I tried to completely mock router -> routerLink directive threw an error

**Comment by satanTime** [comment]
Basically, in unit tests you have a subject under test and the subject should stay as it is, and its dependencies should be mocked.
if you need to mock a part of the subject (unit) - it means bad design of the subject, and maybe they part you want to mock should be an external dependency.

If you have integration tests, then you have 2+ subjects under test and it's the same story - their dependencies should be mocked, but the subjects should stay as they are.

Regarding the error when you mock, I think, it's because not all dependencies have been mocked, especially `routerLink`, otherwise it would be an empty mock which doesn't have logic to throw errors.
An example how a mock `RouterModule` works well with `routerLink`: https://codesandbox.io/s/boring-black-20jj5r?file=/src/test.spec.ts:902-1177
