### ISSUE TITLE
Bug: router.urlHandlingStrategy.extract is not a function

### ISSUE THREAD

**Issue by dexster** [help-me-mom/ng-mocks#4429]
### Description of the bug

Since upgrading to Angular 15 this issue occurs when using RouterModule.

`TypeError: router.urlHandlingStrategy.extract is not a function`

### An example of the bug

Link: https://codesandbox.io/s/goofy-chatelet-4pmxfz?file=/src/test.spec.ts

I have only changed 1 file in your test repro sandbox and have commented in the 2 places I added code.

### Expected vs actual behavior

ng-mocks should use the router module without this error

When using the standard Angular Testbed setup, no errors are experienced

**Comment by satanTime** [comment]
Hi there, 

thanks for reporting.

The solution here is to keep root providers:

```ts
  beforeEach(() => {
    return MockBuilder([
      TargetComponent,
      RouterModule,
      RouterTestingModule.withRoutes([]),
      NG_MOCKS_ROOT_PROVIDERS, // <- this is the fix
    ], TargetModule);
  });
```

more info is in docs: https://ng-mocks.sudo.eu/guides/route

I'll try to emphasize this more explicitly.

**Comment by dexster** [comment]
Thanks. That does solve the issue for the simple repro. Unfortunately, when I add that to my specs all my providers / deps that were previously automatically mocked are no longer mocked and I am getting many NullInjectorError errors: No provider for xxx.

**Comment by satanTime** [comment]
You shouldn't add it to all specs. Only to tests where the router should be kept.

**Comment by dexster** [comment]
Will do. Thanks for the fast replies

**Comment by satanTime** [comment]
[v14.5.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.5.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by satanTime** [comment]
Hi @dexster,

could you tell me your current situation? Is everything okay, or are there issues?

**Comment by dexster** [comment]
Everything is working well.

**Comment by satanTime** [comment]
Hey @dexster, 

Thanks for the update. 
Stay in touch then!
