### ISSUE TITLE
Bug: NG0300 thrown when MockModule and TestBed.overrideModule are used together

### ISSUE THREAD

**Issue by ma7moudat** [help-me-mom/ng-mocks#4641]
### Description of the bug

This occurred while trying to update from v14.4.0 to v14.5.2.

#### Scenario:

- `IconComponent` in `IconModule`.
- `Dummy1Component` in `Dummy1Module`. Imports `IconModule` and renders `IconComponent`.
- `Dummy2Component` in `Dummy2Module`. Imports `IconModule` and renders `IconComponent`.
- `MainComponent` the component to be tested. Renders `Dummy1Component`, `Dummy2Component` and `IconComponent`.
- In the test:
    - `IconComponent` is replaced by `IconMockComponent` using `TestBed.overrideModule()`.
    - `Dummy1Module` is mocked with ng-mocks' `MockModule()`.

#### Result:
An error is thrown:

```sh
Error: NG0300: Multiple components match node with tagname app-icon: IconMockComponent and IconComponent. 
Find more at https://angular.io/errors/NG0300
...
```

Once the `MockModule()` call or the `TestBed.overrideModule()` call is removed, the test passes.

### An example of the bug

Link: https://codesandbox.io/s/gallant-ully-kof3s7?file=/src/test.spec.ts

### Expected vs actual behavior

Not sure TBH, since this error is thrown by Angular by design, but is there a way for the mock from `TestBed.overrideModule()` to take precedence?

In our project we use `TestBed.overrideModule()` in the test setup script to apply some global component mocks and in the tests, we use `MockModule()` for convenience.

**Comment by satanTime** [comment]
[v14.5.3](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.5.3) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
