### ISSUE TITLE
Bug: `MockService` does not respect `ngMocks.defaultMock(...)`

### ISSUE THREAD

**Issue by stefan-niedermann** [help-me-mom/ng-mocks#4738]
### Description of the bug

I created a default mock in our `setup-jest.ts` file which works pretty well when using it in combination with `MockProvider(...)`. However, when instantiating a mocked instance, the default seems not to be respected.

### An example of the bug

Unfortunately confidential, but if it is expected to work or you can not reproduce the issue, I will try to write down a minimal sample.

### Expected vs actual behavior

`MockService` should behave just as `MockProvider` and respect the default I created for a mock using `ngMocks.defaultMock(...)`.

**Comment by satanTime** [comment]
Hi @stefan-niedermann,

`MockService` is for pure js classes and objects : https://ng-mocks.sudo.eu/api/MockService, it doesn't have access to `Injector`, whereas `Injector` is needed for `ngMocks.defaultMock`.

Because of that, there is no way to support `ngMocks.defaultMock` in `MockService`.
