### ISSUE TITLE
Bug: Mocking Guard return null for component since update to Angular v15

### ISSUE THREAD

**Issue by LeonieWV** [help-me-mom/ng-mocks#4822]
### Description of the bug

I have made some tests for a CanDeactivate Guard but after updating to Angular version 15 this test stopped working. It seems like ng mocks cannot find the component that should be accessed by the canDeactive function anymore and gives back null.
Please let me know if there is something I have missed in the updates that can explain why this test is breaking after updating.

### An example of the bug

Example Angular v14 everything works:
https://stackblitz.com/edit/github-qtytqv-sn7qbq?file=src%2Fexamples%2FTestRoutingGuard%2Ftest.spec.ts&initialpath=?spec=TestRoutingGuard

Example Angular 15 not working:
https://stackblitz.com/edit/github-qtytqv?file=src%2Fexamples%2FTestRoutingGuard%2Ftest.spec.ts&initialpath=?spec=TestRoutingGuard

### Expected vs actual behavior

I have read through the release notes from angular and ng-mocks but I haven't seen any indications that this should not be working anymore. So I expected that after the upgrade this test would be fine, all my other tests are.

**Comment by satanTime** [comment]
Hi @LeonieWV,

thank you for reporting the issue, I'll take a look next days what has changed and try to fix that.

**Comment by satanTime** [comment]
Hi @LeonieWV,

there was a change in angular and now you need to pass an empty object as params of `RouterOutlet`:

```ts
const fixture = MockRender(RouterOutlet, {});
```

**Comment by satanTime** [comment]
I've added info to migration guide: https://ng-mocks.sudo.eu/migrations#from-14-to-15

**Comment by LeonieWV** [comment]
@satanTime 

Ahh didn't notice that but thank you for the help!

**Comment by satanTime** [comment]
[v14.7.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.7.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
