### ISSUE TITLE
Feature Request: Never Mock CommonModule standalone directives

### ISSUE THREAD

**Issue by evtk** [help-me-mom/ng-mocks#5047]
### Describe the feature or problem you'd like to solve

I'm currently migrating my Angular app to standalone components and I noticed a lot of UT's failing due to the fact that the standalone Directives from the CommonModule are all mocked. 

If you use the `CommonModule`, this issue doesn't occur, because the `CommonModule` will never be mocked. 

https://github.com/help-me-mom/ng-mocks/commit/119dd80#diff-681237701f19323be249b4715554476ddf90b5f2f81ebbf06e8a7206344048aa

### Proposed solution

Can all the standalone directives from the `CommonModule` also be excluded from mocking. This will prevent to do a 

```     
      .keep(NgIf)
      .keep(NgSwitch)
      .keep(NgSwitchCase)
      .keep(NgFor)
      etc...
```      
in every UT. Many thanks!

### Additional context

Posted this on the gitter as well: https://app.gitter.im/#/room/#ng-mocks_community:gitter.im/$B5OT4_mO-IlFcQHZc7Pg_rYyxm-OxSJBdPx1BNPVkAM

**Comment by satanTime** [comment]
Hi @evtk,

could you provide an example of a failing test?

**Comment by satanTime** [comment]
The example is here: https://stackblitz.com/edit/github-vfxlsb?file=src%2Fexamples%2FTestStandaloneComponent%2Ftest.spec.ts&initialpath=?spec=TestStandaloneComponent

**Comment by satanTime** [comment]
[v14.7.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.7.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by evtk** [comment]
awesome, many thanks. Works like charm!
