### ISSUE TITLE
Artefacts using Directive Composition API

### ISSUE THREAD

**Issue by LukasMachetanz** [help-me-mom/ng-mocks#5117]
Hey!

I guess it is currently not possible to mock artefacts which are applied using the [Directive composition API](https://angular.io/guide/directive-composition-api), right?

Could ng-mocks support this in the near future?

Greets,
Lukas

**Comment by satanTime** [comment]
[v14.8.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.8.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
