### ISSUE TITLE
Bug: Tests failing with Angular 15.2.2

### ISSUE THREAD

**Issue by lgpage** [help-me-mom/ng-mocks#5118]
### Description of the bug

Tests are failing when upgrading to Angular to v15.2.2

See
* https://github.com/lgpage/rxtutor/pull/292
* https://github.com/lgpage/rxtutor/actions/runs/4369954599/jobs/7644339208

Error:
`./node_modules/ng-mocks/index.mjs:879:27-92 - Error: export 'ɵivyEnabled' (imported as '__WEBPACK_EXTERNAL_MODULE__angular_core_bcead0df__') was not found in '@angular/core' (possible exports:`

It looks like the `eivyEnabled` const has been removed: https://github.com/angular/angular/compare/15.2.1...15.2.2#diff-2b5852df25d6ad975ee77aa156106f45e8b17465fd64a0569ef0ed49e3b3a3f0L40

**Comment by logancooper-tylertech** [comment]
We are also seeing this issue. It looks like ng-mocks was referencing what appears to be an internal variable in angular, which got removed in the 15.2.2 patch.

From packages/core/src/core_private_export.ts in the angular project:
```
// TODO(alxhub): allows tests to compile, can be removed when tests have been updated.
export const ɵivyEnabled = true;
```
Which was removed by commit https://github.com/angular/angular/commit/6b9ec0b83065e98a40d2cf6a27ca5c66a7d7c16f as part of merging the PR https://github.com/angular/angular/pull/49296

**Comment by satanTime** [comment]
[v14.7.1](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.7.1) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
