### ISSUE TITLE
Feature Request: Documentation to unit test functional router guard

### ISSUE THREAD

**Issue by qdelettre** [help-me-mom/ng-mocks#5455]
### Describe the feature or problem you'd like to solve

Angular deprecated the use of class based router guard, in favor of functional guard.
I did not find documentation to test router guard of such nature on the reference page (https://ng-mocks.sudo.eu/guides/routing-guard)

### Proposed solution

Writing a documentation for this kind of implementation (functional router guard) will be needed, as more and more developers will follow angular guideline to use such instead of class based guards.

### Additional context

Thanks @satanTime for the message on [gitter](https://matrix.to/#/!pLuPilgOqSgdoZBpGE:gitter.im/$wSZsj18m7m9T4yI_Pq6aDQM8Zm7ElOChM8FP7wphEMk?via=gitter.im).

--
I tried to follow https://ng-mocks.sudo.eu/guides/routing-guard but it does not seems to work (tested canMatchFn & canActivateFn guards)

**Comment by satanTime** [comment]
[v14.10.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.10.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by qdelettre** [comment]
Thanks a lot @satanTime

**Comment by satanTime** [comment]
Always welcome, @qdelettre! 🤘🤘🤘
