### ISSUE TITLE
Bug: Mocking a component declared in a module imported in a standalone component leads to a duplicate declaration exception

### ISSUE THREAD

**Issue by rene-leanix** [help-me-mom/ng-mocks#5491]
### Description of the bug

When mocking a component. which is declared in a module that in turn is imported in a standalone component, this leads to duplicate declarations. (See example and error message below.)

### An example of the bug

Here's a simple test reproducing this issue (also [here on Stackblitz](https://stackblitz.com/edit/github-gzlejl?file=src/test.spec.ts)):

```ts
import { Component, NgModule } from '@angular/core';
import { TestBed } from '@angular/core/testing';
import { MockComponent, MockRender } from 'ng-mocks';

@Component({
  selector: 'my-component',
  template: '',
})
export class MyComponent {}

@NgModule({
  declarations: [MyComponent],
  exports: [MyComponent],
})
export class MyModule {}

@Component({
  selector: 'my-standalone-component',
  standalone: true,
  template: '',
  imports: [MyModule],
})
export class MyStandaloneComponent {}

beforeEach(async () => {
  await TestBed.configureTestingModule({
    imports: [MyStandaloneComponent],
    declarations: [MockComponent(MyComponent)],
  }).compileComponents();
});

it('creates MyStandaloneComponent', () => {
  expect(() => MockRender(MyStandaloneComponent)).not.toThrow();
});
```

For this test, Angular throws the following error message:

> Type MockOfMyComponent is part of the declarations of 2 modules: DynamicTestModule and MockOfMyModule! Please consider moving MockOfMyComponent to a higher module that imports DynamicTestModule and MockOfMyModule. You can also create a new NgModule that exports and includes MockOfMyComponent then import that NgModule in DynamicTestModule and MockOfMyModule..

### Expected vs actual behavior

Expected behavior: no error.

### Current workaround

Importing the module in the testing module config prevents the error:

```ts
  await TestBed.configureTestingModule({
    imports: [MyStandaloneComponent, MyModule],
    declarations: [MockComponent(MyComponent)],
  }).compileComponents();
````

(see [Stackblitz](https://stackblitz.com/edit/github-gzlejl-pgoryn?file=src/test.spec.ts))

It would still be great if this could be fixed, as the workaround may not be immediately apparent to the growing number of Angular devs using standalone components.

The need to import whole modules into standalone-component is quite a common scenario for an existing code base, at it allows to convert higher-order components into standalone components, but also for code using third-party modules that have not yet been converted to standalone components.

**Comment by satanTime** [comment]
Hi there,

it's not a bug, its a wrong definition of the testing module, you'll get the same error without `ng-mocks`: https://stackblitz.com/edit/github-gzlejl-qzrk9z?file=src%2Ftest.spec.ts,src%2Ftest.ts,src%2Fmain.ts

If you want to keep `MyModule` and to mock `MyComponent` only, you should use `MockBuilder`:

```ts
beforeEach(() => MockBuilder([MyStandaloneComponent, MyModule], MyComponent));
```
