### ISSUE TITLE
Bug: mockComponent of standalone component breaks ngIf

### ISSUE THREAD

**Issue by warri93** [help-me-mom/ng-mocks#5957]
### Description of the bug

I have 2 components, 1 standalone component and 1 non standalone component.
My standalone component imports `ngIf` to show a label based on a value. 
My non standalone component also relies on `ngIf` to show a label.

I've written some tests for my non standalone component to verify the label based on a condition. Everything works fine until I mock out my standalone component with `mockComponent`. From this point, my `ngIf` is not working anymore and the label is not being rendered. 

I found 3 solutions for this:
- Import CommonModule in my test
- Import CommonModule instead of NgIf in my standalone component
- Mock component by creating a new component in my test class

To me it feels like when using MockComponent it is taking over the imports specified in the mocked component (when it's a standalone component). Not sure if this is the behaviour we want to have since in the end, I do wanna mock my component to not have any dependencies from it.

I've tested this with the latest version of ngMocks as well, but that gave me the same behaviour.

### An example of the bug

Here you can find a small project which has 2 components (1 standalone and 1 non standalone) and a spec file with the failure (and possible solutions to comment out)

Link: https://github.softwareag.com/melw/ng-mocks-standalone-component

### Expected vs actual behaviour

When using MockComponent I would expect my imports in the standalone component to be ignored so that it doesn't effect my existing tests in my non standalone component. Making sure `ngIf` still works as expected, no matter what the mocked component looks like.

Thanks for having a look at this!

Kind regards,
Melissa

**Comment by satanTime** [comment]
Hi @warri93,

it looks like, your project doesn't have installation instructions: https://ng-mocks.sudo.eu/extra/install

This part:

```ts
// Usually, *ngIf and other declarations from CommonModule aren't expected to be mocked.
// The code below keeps them.
import { CommonModule } from '@angular/common'; // eslint-disable-line import/order
import { ApplicationModule } from '@angular/core'; // eslint-disable-line import/order
import { BrowserModule } from '@angular/platform-browser'; // eslint-disable-line import/order
ngMocks.globalKeep(ApplicationModule, true);
ngMocks.globalKeep(CommonModule, true);
ngMocks.globalKeep(BrowserModule, true);
```

**Comment by warri93** [comment]
Hi @satanTime,

Can you give me a bit more details on this?
I understand that adding this to our test setup makes our tests green again but I do not fully understand why we explicitly need to this.

When I do not mock my standalone component through ngmocks all my tests are running fine but when using mockComponent they suddenly start to fail because of the imports in the standalone component (which is exactly the reason why I want to mock this component). 

I do not want to think about all the imports in my mocked component since they don't bring any advantages to my test. Meaning I would expect that my test would ignore the imports that I've added in the standalone component so my tests are not dependent on it. 

Am I not seeing something here?

Thanks!

**Comment by satanTime** [comment]
You ned this, because dependencies of your components aren't defined correctly. In this example, the SUT doesn't import `CommonModule`. Because `ngIf` is a dependency of a mock component, but not a dependency of the SUT, `ng-mocks` mocks it.

To avoid that, you should explicitly specify `CommonModule` as a dependency of the SUT, basically, what you say in the description of the bug. Then `NgIf` will stay as kept.

Another thing, If you don't want to think about all the imports, then you don't need `ng-mocks` :) simply import / declare a stub component with empty dependencies.
The idea of `ng-mocks` is to mock all dependencies to suppress their logic, and the reason behind is that a dependency can provide additional directives, tokens and services which can be used in the SUT, and removing them would break it.

**Comment by warri93** [comment]
Ok, that makes completely sense indeed! 
Thanks for clarifying this for us and answering this quickly!
