### ISSUE TITLE
Bug: Unable to mock providers of a standalone component

### ISSUE THREAD

**Issue by Julien-Marcou** [help-me-mom/ng-mocks#5968]
### Description of the bug

After converting a Single Component Angular Module (SCAM) to a Standalone component, I'm unable to mock providers for the component.

### An example of the bug

My component before (SCAM):

```ts
@Component({
  selector: 'foo',
  templateUrl: './foo.component.html',
  styleUrls: ['./foo.component.scss'],
})
export class FooComponent {
  constructor(@Inject(SERVICE_TOKEN) private service: FooService) {
    this.service.init();
  }
}

@NgModule({
  declarations: [FooComponent],
  exports: [FooComponent],
  imports: [CommonModule],
  providers: [
    {
      provide: SERVICE_TOKEN,
      useClass: FooService,
    },
  ],
})
export class FooComponentModule {}
```

My component now (standalone):

```ts
@Component({
  standalone: true,
  selector: 'foo',
  templateUrl: './foo.component.html',
  styleUrls: ['./foo.component.scss'],
  imports: [CommonModule],
  providers: [
    {
      provide: SERVICE_TOKEN,
      useClass: FooService,
    },
  ],
})
export class FooComponent {
  constructor(@Inject(SERVICE_TOKEN) private service: FooService) {
    this.service.init();
  }
}
```

The unit test:

```ts
describe('CrateReviewCategoryComponent', () => {
  let fixture: MockedComponentFixture<FooComponent>;

  const fooServiceMock = {
    init: jest.fn(),
  };

  beforeEach(() =>
    // Before being it standalone component, it was:
    // MockBuilder(FooComponent, FooComponentModule)
    //  .provide({ provide: SERVICE_TOKEN, useValue: fooServiceMock })
    
    // Now it's:
    MockBuilder(FooComponent)
      .provide({ provide: SERVICE_TOKEN, useValue: fooServiceMock })
  );

  beforeEach(() => {
    fixture = MockRender(FooComponent);
  });

  it('should init the service', () => {
    expect(fooServiceMock.init).toHaveBeenCalled();
  });
});
```

### Expected vs actual behavior

For some reason, while it was working with a SCAM, it looks like the FooService does not get mocked at all with a standalone component and I get the following error:

```shell
TypeError: Cannot read properties of undefined (reading 'init')
```

Am I doing something wrong, or is it something not supported by `ng-mocks` ?

**Comment by Julien-Marcou** [comment]
Well, looks like you have to use `mock()` for this case, instead of `provide()`, but TypeScript had a hard time figurine out which signature of `mock()` to use, so it was showing typing errors, to fix the typing errors I had to help it a bit with:


```ts
  const fooServiceMock = {
    init: jest.fn(),
  } as unknown as FooService;

  beforeEach(() =>
    MockBuilder(FooComponent).mock<FooService>(SERVICE_TOKEN, fooServiceMock)
  );
```

Hopefully it can help other people in the future 😅

**Comment by satanTime** [comment]
Hi @Julien-Marcou,

I'm glad to hear you figured out how to solve it.

Could you share the type of `SERVICE_TOKEN`?
Usually, `.mock` should catch its generic type correctly, but, maybe that should be tuned.

**Comment by Julien-Marcou** [comment]
Oh my fucking god, I'm so dumb, I tried for 1h to make a small reproduction without being able to, so I started reproducing my entire code bit by bit, which is much more complexe, as the service is a generic interface, and in my case I have several components which are provided with different implementations of the service.

And it worked...

The problem was that I had two types with the same name, and I was importing the wrong type for the token declaration -___-

I had something like:


```ts
export interface GenericService<T> {
  // ...
}
```

```ts
import { MyType } from '../WRONG-module/my-type';

export const SERVICE_TOKEN = new InjectionToken<GenericService<MyType>>('SERVICE_TOKEN');
```

```ts
import { MyType } from '../CORRECT-module/my-type';

export class FooService implements GenericService<MyType> {
  // ...
}
```

If I had better typed my generic interface with:

```ts
import { MyType } from '../CORRECT-module/my-type';

export interface GenericService<T extends MyType> {
  // ...
}
```

I would have seen the problem earlier.


Sorry for the disturbance 😅

**Comment by satanTime** [comment]
Aha :) what a nice catch :) Then great stay in touch!

Let me know if you have any other feedback / feature request about `ng-mocks`, I'm more than happy to discuss them.
