### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by rezres** [help-me-mom/ng-mocks#6063]
### Description of the bug

Using Mock-Component to mock any component is causing other unrelated components that are explicitly declared in test modules configuration to be mocked as well, this is unexpected behavior because the component was explicitly declared in the test module and we are not expecting it to be mocked in any context within the test suit. 

More info can be found in this [SO Question](https://stackoverflow.com/questions/76458584/weird-behavior-after-updating-ng-mocks-testbed-create-component-behavior-change)

### An example of the bug
[You can find the example here](https://github.com/rezres/ng-mocks-issue-repro/tree/master)

### Expected vs actual behavior

in the provided example, we have app component, and wrapper component, wrapper component's template includes app component instance.
 
Expected: when we create an instance of wrapper component, a real instance of app component should be instantiated since it's part of wrapper component and it was explicitly declared within the test bed module. 

Actual:  when we create an instance of wrapper component, an empty mocked instance of app component is created. 

The issue is linked to MockComponent usage, the issue wasn't present on older version of ng mock (13.0) 

I hope that you find this info helpful. 

Best regards.

**Comment by satanTime** [comment]
Hi @rezres,

the issue here is that `test-helpers.ts` is a partial copy-paste of `ng-mocks` sources, because of that `ng-mocks` detects `wrapper` as a mock of `AppComponent`.

To fix this, delete the line 7 in `test-helpers.ts`:
```
mockOf: { value: mockClass },
```
