### ISSUE TITLE
Docs: Rename testing guide NGRS to NGXS

### ISSUE THREAD

**Issue by mfrieling** [help-me-mom/ng-mocks#6356]
There's a repeated typo in the docs (testing guides): The second state management library besides NGRX is **not NGRS** but NGXS**. Due to this typo I couldn't find it and had to find out how to test the state on my own with a lots of problems and a way more complex final result than in the docs.

In addition, the example doesn't work for me, I get the error message
> Cannot find an instance via ngMocks.findInstance(Store)

I'm using 
- Angular: 16.1.6 **(Standalone)**
- @nx/angular: 16.3.2 (NX workspace with Angular preset and module federation)
- @ngxs/store: 3.8.1
- Jest: 29.5.0
- ng-mocks: 14.11.0

**Comment by satanTime** [comment]
Hi @mfrieling,

thanks for noting, such a silly typo...

**Comment by satanTime** [comment]
[v14.12.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.12.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
