### ISSUE TITLE
Bug: ngMocks.globalReplace() doesn't work

### ISSUE THREAD

**Issue by mfrieling** [help-me-mom/ng-mocks#6402]
### Description of the bug

Using Jest, `ngMocks.globalReplace()` in `test-setup.ts` doesn't work as expected, compared to `MockBuilder(MyComponent).replace(HttpClientModule, HttpClientTestingModule)`.

If you have a lot of tests (tested components, services etc.) which depend on _HttpClientModule_, instead of repeating `MockBuilder(MyComponent).replace(HttpClientModule, HttpClientTestingModule)` in every spec you instead want to just write `MockBuilder(MyComponent)` and put a `ngMocks.globalReplace(HttpClientModule, HttpClientTestingModule)` into `test-setup.ts`.

But this doesn't work as expected.

### An example of the bug

`test-setup.ts`:
```
// Jest configuration skipped here for simplicity.

ngMocks.autoSpy('jest')

ngMocks.globalKeep(ApplicationModule, true)
ngMocks.globalKeep(CommonModule, true)
ngMocks.globalKeep(BrowserModule, true)
ngMocks.globalKeep(RouterModule, true)

//ngMocks.globalReplace(HttpClientModule, HttpClientTestingModule)
```

`app.component.spec.ts`:
```
describe('AppComponent', () => {
  beforeEach(async () =>
    MockBuilder(AppComponent)
      .replace(HttpClientModule, HttpClientTestingModule)
      .keep(RouterTestingModule.withRoutes([])),
  )

  test('should create the app', () => {
    const fixture = MockRender(AppComponent)

    expect(fixture.point.componentInstance).toBeDefined()
  })
})
```

### Expected vs actual behavior

This test passes. If I now comment out the `.replace()` line in the spec file and uncomment the corresponding line `ngMocks.globalReplace()` the test should still pass.

Instead I get the following error:
> ● AppComponent › should create the app
>
> NullInjectorError: R3InjectorError(DynamicTestModule)[WorkflowManagerService -> WorkflowManagerApiService -> AssetLoaderService -> _HttpClient -> _HttpClient]:
>   NullInjectorError: No provider for _HttpClient!

**Comment by satanTime** [comment]
Hi @mfrieling,

thanks for reporting. The issue will be fixed with the next release.

**Comment by satanTime** [comment]
[v14.12.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.12.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by cluxig** [comment]
Still the same issue for version `14.12.1`. I tried `ngMocks.globalReplace(HttpClientModule, HttpClientTestingModule);` and `ngMocks.globalKeep(HttpClientTestingModule, true)`. Both resulting in `HttpClient` not provided. 

Whereas using `.replace(HttpClientModule, HttpClientTestingModule)` or `.keep(HttpClientTestingModule)` directly on `MockBuilder` works as expected.

**Comment by Eagl9Eye** [comment]
@satanTime should a new issue be opened?
