### ISSUE TITLE
Bug: MockInstance doesn't manipulate the instance (findInstance works though)

### ISSUE THREAD

**Issue by craiggoldstone** [help-me-mom/ng-mocks#6791]
### Description of the bug

`MockInstance(MockStore, (store) => ...)` isn't manipulating the instance, or even executing that code (tested with a console.log). Switching to `TestBed.inject(MockStore)` or `ngMocks.findInstance(MockStore)` I can get the test to pass. Possibly related to https://github.com/help-me-mom/ng-mocks/issues/6556.

Additionally I am using NgRx testing functions `provideMockStore` and `overrideSelector` on a standalone component with a very simple feature selector.

At first I thought I was misunderstanding MockInstance like [this StackOverflow question](https://stackoverflow.com/questions/69035990/how-can-i-manipulate-providers-in-specific-tests-using-ng-mocks) however their issue was calling MockInstance *after* MockRender, and that's not happening here.

I'm not sure if this an NgRx thing, or a ng-mocks thing. The [ng-mocks guide for NgRx](https://ng-mocks.sudo.eu/guides/libraries/ngrx) doesn't mention MockInstance or overrideSelector so once this issue is resolved perhaps it's including as an example too.

### An example of the bug
Link: https://stackblitz.com/edit/github-uqhvpu?file=src%2Ftest.spec.ts

### Expected vs actual behavior
Expected:
```
interface FooState {
  bar: string;
}

const selectFoo = (state: { foo: FooState }) => state.foo;
const selectBar = createSelector(selectFoo, (foo) => foo.bar);

@Component({
  selector: 'app-foo',
  standalone: true,
  template: `<pre>{{ bar$ | async }}</pre>`,
  imports: [AsyncPipe],
})
class FooComponent {
  private store = inject(Store);
  bar$ = this.store.select(selectBar);
}

describe('my sandbox', () => {
  MockInstance.scope();

  beforeEach(() =>
    MockBuilder(FooComponent).keep(AsyncPipe).provide(provideMockStore())
  );

  it('should override the selector', () => {
    MockInstance(MockStore, (store) => {
      store.overrideSelector(selectBar, 'BAR');
    });
    const fixture = MockRender(FooComponent);
    expect(fixture.point.nativeElement.innerHTML).toContain('<pre>BAR</pre>');
  });
});
```

Actual:
```
1 spec, 1 failure
[Spec List](https://github-uqhvpu.stackblitz.io/#) | Failures
my sandbox > should override the selector
Expected '<pre></pre>' to contain '<pre>BAR</pre>'.
```

**Comment by satanTime** [comment]
Hi @craiggoldstone,

you are right. This is the same misunderstanding as in https://github.com/help-me-mom/ng-mocks/issues/6556.
Please read the answer there it explains why `MockStore` is not a mock.

Also, if you have further questions, feel free to write a comment or reopen the issue.
