### ISSUE TITLE
MockInstance is not clear how spy methods get assigned Bug: 

### ISSUE THREAD

**Issue by dezmon-fernandez** [help-me-mom/ng-mocks#6906]
### Description of the bug
When MockInstance is called in beforeEach and a spy is assigned to a method, the spy is unretrievable in spec. 
The below example fails because it says the setGraphParamsSpy was never called.

### An example of the bug
```
  beforeEach(() => {
    MockInstance(SocialNetworkRepostiory, () => ({
      graphLoading$: of(false),
      graphParameters$: of(null),
      setGraphParams: jasmine.createSpy('setGraphParams'),
    }));
    MockInstance(PersonasService, () => ({
      getBulkPersonas$: jasmine.createSpy('getBulkPersonas$').and.returnValue(of([])),
    }));
  });

it('should call spy', () -> {
    const socialNetworkRepo = ngMocks.findInstance(SocialNetworkRepostiory);
    const setGraphParamsSpy = socialNetworkRepo.setGraphParams as jasmine.Spy;
   const fixture = MockRender(SocialNetworkComponent, {
      data
    });
    expect(setGraphParamsSpy).toHaveBeenCalled();
})
```

Here is a working example....
```
  beforeEach(() => {
    MockInstance(SocialNetworkRepostiory, () => ({
      graphLoading$: of(false),
      graphParameters$: of(null),
      setGraphParams: jasmine.createSpy('setGraphParams'),
    }));
    MockInstance(PersonasService, () => ({
      getBulkPersonas$: jasmine.createSpy('getBulkPersonas$').and.returnValue(of([])),
    }));
  });

it('should call spy', () -> {
    const setGraphParamsSpy = jasmine.createSpy('setGraphParams');
    MockInstance(SocialNetworkRepostiory, 'setGraphParams', setGraphParamsSpy);
   const fixture = MockRender(SocialNetworkComponent, {
      data
    });
    expect(setGraphParamsSpy).toHaveBeenCalled();
})
```
 I dont understand why i cant retrieve the original spy. I tried doing something similar where i injected the service and retrieved the spy to decorate the return value. 
ie
```
const service = ngMocks.get(SomeService);
service.spy.and.returnValue('someOthervalue')
```
and the test only returned the original value. Is this as expected? Is there a way to retrieve the original spy?

**Comment by satanTime** [comment]
Hi @dezmon-fernandez,

the answer on your question is in the first sentence of documentation: https://ng-mocks.sudo.eu/api/MockInstance
> before the desired instance have been created.

In the second example, which works, you call `MockRender` after `MockInstance`, whereas in the first one there is neither `MockRender` nor `TestBed.createComponent`, so I assume they are called before `MockInstance` and, therefore, `MockInstance` doesn't have an effect.
