### ISSUE TITLE
Bug: MockInstance.scope(); is mentioned in "Getting started" doc although being unnecessary nowadays(?)

### ISSUE THREAD

**Issue by rklec** [help-me-mom/ng-mocks#7040]
### Description of the bug
I am a new user to this tool. To quickly get started I let an AI (JetBrains AI Assistant in my case) convert my old code to ng-mocks code (after failing/being annoyed to do so manually). This was greatly successful.
And yes, I did read the docs during that anyway.

### An example of the bug

The getting started page explains `MockInstance.scope();` directly at the beginning and I would be under the impression this is needed.
However, the AI told me:
> In ng-mocks, `MockInstance.scope` is used to clean up the old instances of the mocked objects between each test. However, since `ng-mocks@8.1.0`, this functionality is built-in and by default applicable.

In my experience, it is rare the AI argues against you thus I would assume this is true. or did it talk wrong stuff?

Link: https://ng-mocks.sudo.eu/

### Expected vs actual behavior

If this is true, your doc maybe should not do that anymore? At least not explain it as if it would be obligatory.

The relevant AI transcript snippet:

User: 
Alos should not I add `MockInstance.scope();`?

Assistant: 
No, in ng-mocks, `MockInstance.scope` is used to clean up the old instances of the mocked objects between each test. However, since `ng-mocks@8.1.0`, this functionality is built-in and by default applicable.
  
Therefore, you might not need to call `MockInstance.scope()` to clean up your mocks between test runs.

Here's a simple modification you can make to your test:

```typescript
// [removed by me manually]

describe('[removed by me manually]', () => {
  let component: [removed by me manually]<unknown>;
  let fixture: MockedComponentFixture<[removed by me manually]<unknown>>;

  // MockInstance.scope(); You do not need this line anymore with ng-mocks version 8.1.0 onwards

  beforeEach(() => {
    return MockBuilder([removed by me manually])
      .keep(ReactiveFormsModule)
      .keep(FormsModule)
      .keep(HttpClientTestingModule)
      .keep(RouterTestingModule.withRoutes([]))
      .provide({
        provide: HttpRepository,
        useClass: HttpRepositoryStub,
      })//[removed by me manually]
      // keep other modules
  });

  beforeEach(() => {
    fixture = MockRender(/* [removed by me manually] */);
    component = fixture.point.componentInstance;
    // [removed by me manually]
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```
This ensures that your tests are set up correctly and will clean up after each test run without explicitly having to call `MockInstance.scope()`.

**Comment by satanTime** [comment]
Hi @rklec,

that's partially true and `ng-mocks` used to create and destroy scopes automatically.
However, due to recent changes in `jest`, it became impossible, and, in case of jest, scopes should be created and destroyed manually.

The guide how to configure automatic scopes for `jasmine` is here: https://ng-mocks.sudo.eu/extra/install
The issue in `jest` is here: https://github.com/jestjs/jest/issues/11483.

**Comment by rklec** [comment]
Okay, but then this should be documented? That it is only needed for jest?

**Comment by satanTime** [comment]
By default `ng-mocks` doesn't do that out of shelf, developers should manually add code to `src/test.ts`.

**Comment by satanTime** [comment]
Maybe I don't get your idea, could you explain the problem in more details? 

Basically by default everybody should use `scopes` if they want to use `MockInstance`, and if they want to reduce repetition and they use `jasmine`, then they can configure `test.ts` to create scope automatically.

**Comment by rklec** [comment]
Hmm are the docs on GitHUb? I could create a PR?

**Comment by satanTime** [comment]
Yep - each doc page has `[Edit this page]` link.

**Comment by satanTime** [comment]
[v14.12.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.12.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
