### ISSUE TITLE
Bug: Angular 16 ngMocks.findInstance swallows original error

### ISSUE THREAD

**Issue by CSchulz** [help-me-mom/ng-mocks#7041]
### Description of the bug

If there is an error with the provider factory during the tests ngMocks.findInstance swallows the original error and shows `Cannot find an instance via ngMocks.findInstance(...)` only.
This requires debugging into ng-mocks to find the root cause.

### An example of the bug

https://stackblitz.com/edit/github-6z37vt?file=src%2Ftest.spec.ts

### Expected vs actual behavior

Expected: Show also the original error if there is one.

`Cannot find an instance via ngMocks.findInstance(...). Caught an error during the injection call: <original error>`.

Actual: `Cannot find an instance via ngMocks.findInstance(...)`

**Comment by satanTime** [comment]
Hi @CSchulz,

thanks for reporting the issue. It will be fixed with the next release.

**Comment by satanTime** [comment]
[v14.12.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.12.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
