### ISSUE TITLE
Bug: MockedComponentFixture is actually assignable to ComponentFixture contrary to what doc says

### ISSUE THREAD

**Issue by rklec** [help-me-mom/ng-mocks#7132]
### Description of the bug

[This doc](https://ng-mocks.sudo.eu/api/MockRender#returned-type) says in a big yellow warning:
> The fixture of MockRender(Component) is not assignable to ComponentFixture<Component>.
>
>Its type is MockedComponentFixture<Component>.

However, in my testing actually it is.

### An example of the bug

```ts
    const testFixure: ComponentFixture<TargetComponent> = TestBed.createComponent(TargetComponent);
```

Link: https://stackblitz.com/edit/github-uhckew?file=src%2Ftest.spec.ts

### Expected vs actual behavior

IMHO, as this causes bugs (as you usually do not want your test fixture to be mocked, it should _not_ be assignable?
Because you should not mock the system under test (SUT) that you want to test. For obvious reasons...

I only noticed this problem, because I fall into this trap.

Alternative solution: Adjust the doc. That would be the minimum IMHO.

**Comment by satanTime** [comment]
Hi @rklec,

something is wrong here, in your example you don't use `MockRender` for `testFixure`.

if you change code to use `MockRender`

```
    const fixture: ComponentFixture<TargetComponent> = MockRender(TargetComponent, {
      name: 'sandbox',
      click: spy,
    });
```

, then you'll get

```
Type 'MockedComponentFixture<TargetComponent, { name: string; click: Spy<Func>; }>' is not assignable to type 'ComponentFixture<TargetComponent>'.
```

**Comment by rklec** [comment]
Ypu're right. I thought with `MockBuilder` that was somehow implicitly done.

**Comment by satanTime** [comment]
The best approach is to avoid explicit type here and simply use `cost fixture = MockRender(Component)`.

This warning was added for default test templates, where `let fixture: ComponentFixture<Component>;` is defined in `describe` blocks.
