### ISSUE TITLE
Bug: Unable to install ng-mocks with Angular 17

### ISSUE THREAD

**Issue by berkon** [help-me-mom/ng-mocks#7225]
### Description of the bug

I've just moved to Angular 17, but now when doing `npm install ng-mocks --save-dev` I'm getting:

![image](https://github.com/help-me-mom/ng-mocks/assets/28842661/d51b7892-9ace-4b4c-85bb-142849014a44)

Any idea?

**Comment by mlz11** [comment]
Same issue here ✋🏻

**Comment by StefanNedelchev** [comment]
ng-mocks just needs to migrate to angular 17, we have to wait

**Comment by satanTime** [comment]
Hi all.

There is an issue in Angular 17 which should be fixed first: https://github.com/angular/angular/issues/52817
Feel free to upvote it.

**Comment by berkon** [comment]
I've further investigated the issue and found a workaround which is acceptable for us. The `@angular-eslint` module uses the `@nx/nx-linux-x64-gnu` module. But this module is listed as an optional dependency in `package-lock.json`. Up to now we were using the `–omit=optional` parameter in our GitHub workflows for the `npm ci ...` command lines. This caused the workflows to fail. When removing that parameter everything works fine, because now it allows to install optional modules as well. We only have a few optional modules thus the install time does not increase significantly.

**Comment by PieterjanDeClippel** [comment]
@satanTime What are the prospects of an angular 17 release?

**Comment by satanTime** [comment]
I need to fix two bugs first. So I would say this weekend.

**Comment by k3nsei** [comment]
For those who want to migrate anyways you can put code below to your `package.json`

```json
{
  // ...
  "overrides": {
    "ng-mocks": {
      "@angular/common": "^17.0.2",
      "@angular/core": "^17.0.2",
      "@angular/forms": "^17.0.2",
      "@angular/platform-browser": "^17.0.2"
      }
    }
  }
}
```

**Comment by jase88** [comment]
Thanks - you can also reference existing versions with $

```json
{
  "overrides": {
    "ng-mocks": {
      "@angular/common": "$@angular/common",
      "@angular/core": "$@angular/core",
      "@angular/forms": "$@angular/forms",
      "@angular/platform-browser": "$@angular/platform-browser"
    }
  }
```

**Comment by satanTime** [comment]
[v14.12.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.12.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by berkon** [comment]
Thanks a lot @satanTime !
