### ISSUE TITLE
Update docs about animation

### ISSUE THREAD

**Issue by satanTime** [help-me-mom/ng-mocks#7466]
Thanks @satanTime !

I did not thought `await fixture.whenStable();` was required in order to "skip" animations but it works with it, so this is the only thing I missed in my unit test !
Maybe an extra explanation in this page could helps: https://ng-mocks.sudo.eu/troubleshooting/browser-animations-module

_Originally posted by @Dji75 in https://github.com/help-me-mom/ng-mocks/discussions/7058#discussioncomment-7590164_

**Comment by Duggi-Niharika-Sai-06** [comment]
Is this issue still there? if yes, could you please assign this to me?

**Comment by satanTime** [comment]
Hi @Duggi-Niharika-Sai-06, it is.

Thanks for the desire to help. Please check the related discussion above.

**Comment by satanTime** [comment]
[v14.12.0](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.12.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by Duggi-Niharika-Sai-06** [comment]
could. you please assign this to me?

**Comment by Dji75** [comment]
Thanks @satanTime  ;)

Duggi seems to be a chat bot 😀

**Comment by satanTime** [comment]
💯 🤣

**Comment by Duggi-Niharika-Sai-06** [comment]
Apologies I am a student I am starting to understand it and work on it, this is one of my university assignment to contribute to open source repositories please assign this to me and I will start working asap

**Comment by satanTime** [comment]
Hi @Duggi-Niharika-Sai-06, thank you for the clarification. Unfortunately, this task has been solved and closed already.
