### ISSUE TITLE
update links in the repo

### ISSUE THREAD

**Issue by satanTime** [help-me-mom/ng-mocks#7846]
need to replace `ike18t` with `help-me-mom` in the source code to update links to the current repo.
refs to the user profile `@ike18t` shouldn't be touched.

**Comment by JsantosDK** [comment]
Opened the [PR](https://github.com/help-me-mom/ng-mocks/pull/7999) for this.

**Comment by satanTime** [comment]
[v14.12.2](https://github.com/help-me-mom/ng-mocks/releases/tag/v14.12.2) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
